[package]
name = "AoC_2020_day_01"
version = "0.1.0"
authors = ["Ed Cragg <ed.cragg@eipi.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aocf = { git = "https://github.com/nuxeh/aocf" }
